### ISSUE TITLE
Fix Kiiroo Onyx/Pearl implementation to use bluetooth le "serial" protocol

### ISSUE THREAD

**Issue by qdot** [buttplugio/buttplug-csharp#74]
I think I'm missing some sort of initialization block that makes the kiiroo work over ble instead of bt2 or something. Buttplug will connect, but sending signals doesn't work. I have the same problems going from LightBlue on macOS too.

**Comment by blackspherefollower** [comment]
@qdot Is this fixed by 7480c95a7c19af0cf3b9c0bb140cf0bae13d58fa?

**Comment by qdot** [comment]
@blackspherefollower Nope. That was just me getting the characteristics in the correct order. They still don't actually work. We can icebox this for now though, as I don't know anyone who has an Onyx that's not also a developer. If someone brings it up on our message boards, it might get promoted.

**Comment by qdot** [comment]
Fixed in 3c1215cc

**Comment by blackspherefollower** [comment]
Technically I still haven't cracked the Pearl yet...
